# Bus I2C (MPU6050)
CONFIG_I2C=y

# Bus SPI + GPIO (Nokia 5110)
CONFIG_SPI=y
CONFIG_GPIO=y

# Capteur MPU6050
CONFIG_SENSOR=y
CONFIG_MPU6050=y

# printf avec des float (%.2f)
CONFIG_CBPRINTF_FP_SUPPORT=y

# Logs sur le port série
CONFIG_LOG=y
CONFIG_MAIN_STACK_SIZE=4096